spring.application.name=beer-service
com.brewery.beer-inventory-service-host=http://localhost:8082
logging.level.com.brewery=debug
spring.datasource.initialization-mode=EMBEDDED
spring.jpa.defer-datasource-initialization=true
